"""M2 产品协议模型。

当前仅包含 pre-G7 的协议与 Schema 准备，不启动 HTTP server，不获取 Runtime lease。
"""

from openbimagent.server.correlation_identity import (
    M2_CORRELATION_ID_PATTERN,
    M2_CORRELATION_ID_POLICY_VERSION,
    is_m2_correlation_id,
    validate_m2_correlation_id,
)
from openbimagent.server.control_preflight import (
    M2_CONTROL_PREFLIGHT_VERSION,
    M2ControlPreflight,
    M2ControlPreflightError,
    M2ControlProxyPlan,
    M2ControlRole,
    M2IdempotencyDecision,
    M2IdempotencyDisposition,
    M2IdempotencyFact,
)
from openbimagent.server.contracts import (
    M2_API_PROTOCOL_VERSION,
    M2_ERROR_RETRY_POLICY_VERSION,
    M2_SSE_PROTOCOL_VERSION,
    M2ApiEnvelope,
    M2ApiError,
    M2ArtifactMetadata,
    M2ControlOperation,
    M2ControlRequest,
    M2ErrorCode,
    M2SseCursor,
    M2SseEvent,
    M2SseEventType,
    m2_error_is_retryable,
    make_m2_api_error,
)
from openbimagent.server.idempotency_transaction import (
    M2_IDEMPOTENCY_TRANSACTION_VERSION,
    M2IdempotencyCasCommand,
    M2IdempotencyRecord,
    M2IdempotencyRecordState,
    M2IdempotencyTransaction,
    M2IdempotencyTransactionDecision,
    M2IdempotencyTransactionDisposition,
    M2IdempotencyTransactionError,
)
from openbimagent.server.openapi import (
    M2_OPENAPI_INFO_VERSION,
    M2_OPENAPI_VERSION,
    build_m2_readonly_openapi,
    canonical_openapi_bytes,
    canonical_openapi_sha256,
)
from openbimagent.server.payload_privacy import (
    M2_REMOTE_PAYLOAD_POLICY_VERSION,
    RemotePayloadPrivacyError,
    validate_remote_payload,
)
from openbimagent.server.resource_identity import (
    M2_RESOURCE_ID_PATTERN,
    M2_RESOURCE_ID_POLICY_VERSION,
    is_m2_resource_id,
    validate_m2_resource_id,
)
from openbimagent.server.readonly_http import (
    M2_READONLY_HTTP_ADAPTER_VERSION,
    M2_READONLY_REQUEST_METADATA_BUDGET,
    M2HttpHeader,
    M2ReadonlyHttpAdapter,
    M2ReadonlyHttpRequest,
    M2ReadonlyHttpResponse,
    m2_error_http_status,
)
from openbimagent.server.service import M2_READONLY_SERVICE_VERSION, M2ReadOnlyService
from openbimagent.server.sse_identity import (
    M2_SSE_STREAM_ID_PATTERN,
    M2_SSE_STREAM_ID_POLICY_VERSION,
    is_m2_sse_stream_id,
    validate_m2_sse_stream_id,
)
from openbimagent.server.sse_projection import (
    M2_SSE_PROJECTION_VERSION,
    M2SseProjector,
    SseProjectionError,
)

__all__ = [
    "M2_API_PROTOCOL_VERSION",
    "M2_CONTROL_PREFLIGHT_VERSION",
    "M2_CORRELATION_ID_PATTERN",
    "M2_CORRELATION_ID_POLICY_VERSION",
    "M2_ERROR_RETRY_POLICY_VERSION",
    "M2_IDEMPOTENCY_TRANSACTION_VERSION",
    "M2_OPENAPI_INFO_VERSION",
    "M2_OPENAPI_VERSION",
    "M2_READONLY_HTTP_ADAPTER_VERSION",
    "M2_READONLY_REQUEST_METADATA_BUDGET",
    "M2_READONLY_SERVICE_VERSION",
    "M2_REMOTE_PAYLOAD_POLICY_VERSION",
    "M2_RESOURCE_ID_PATTERN",
    "M2_RESOURCE_ID_POLICY_VERSION",
    "M2_SSE_PROJECTION_VERSION",
    "M2_SSE_PROTOCOL_VERSION",
    "M2_SSE_STREAM_ID_PATTERN",
    "M2_SSE_STREAM_ID_POLICY_VERSION",
    "M2ApiEnvelope",
    "M2ApiError",
    "M2ArtifactMetadata",
    "M2ControlOperation",
    "M2ControlPreflight",
    "M2ControlPreflightError",
    "M2ControlProxyPlan",
    "M2ControlRequest",
    "M2ControlRole",
    "M2ErrorCode",
    "M2IdempotencyCasCommand",
    "M2IdempotencyDecision",
    "M2IdempotencyDisposition",
    "M2IdempotencyFact",
    "M2IdempotencyRecord",
    "M2IdempotencyRecordState",
    "M2IdempotencyTransaction",
    "M2IdempotencyTransactionDecision",
    "M2IdempotencyTransactionDisposition",
    "M2IdempotencyTransactionError",
    "M2HttpHeader",
    "M2ReadonlyHttpAdapter",
    "M2ReadonlyHttpRequest",
    "M2ReadonlyHttpResponse",
    "M2SseCursor",
    "RemotePayloadPrivacyError",
    "M2ReadOnlyService",
    "M2SseEvent",
    "M2SseProjector",
    "M2SseEventType",
    "SseProjectionError",
    "build_m2_readonly_openapi",
    "canonical_openapi_bytes",
    "canonical_openapi_sha256",
    "is_m2_correlation_id",
    "is_m2_resource_id",
    "is_m2_sse_stream_id",
    "m2_error_http_status",
    "m2_error_is_retryable",
    "make_m2_api_error",
    "validate_m2_correlation_id",
    "validate_m2_resource_id",
    "validate_m2_sse_stream_id",
    "validate_remote_payload",
]
